name: InterfazGraficaRobotENV
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - icu=58.2
  - ipykernel=6.25.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - libclang=14.0.6
  - libclang13=14.0.6
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - openssl=3.0.12
  - packaging=23.1
  - parso=0.8.3
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyserial=3.5
  - python=3.11.7
  - python-dateutil=2.8.2
  - pywin32=305
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - spyder-kernels=2.4.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2023d
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - numpy==1.26.3
      - opencv-python==4.9.0.80
      - pyrealsense2==2.54.2.5684
