name: intRACE_ENV
channels:
  - defaults
dependencies:
  - python==3.8.18
  - numpy=1.24.3
  - pip=23.3.1
  - pyqt=5.15.10
  - pyserial=3.5
  - spyder-kernels=2.4.4
  - pip:
    - opencv-python-headless==4.9.0.80
    - pyrealsense2==2.54.2.5684
