name: intRACE_ENV
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2023.12.12
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - icu=73.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.12.2
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - libclang=14.0.6
  - libclang13=14.0.6
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.5.6
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.12
  - packaging=23.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyserial=3.5
  - python=3.8.18
  - python-dateutil=2.8.2
  - pywin32=305
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - spyder-kernels=2.4.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - opencv-python-headless==4.9.0.80
      - pyrealsense2==2.54.2.5684
